import 'dart:io';
import 'package:path/path.dart' as p;

void main() {
  final files = [
    'list.dart',
    'mark.dart',
    'errors.dart',
    'patterns.dart',
    'grammar.dart',
    'state_machine.dart',
    'sppf.dart',
    'bsr.dart',
    'sm_parser.dart',
  ];

  final srcDir = Directory('lib/src');
  final imports = StringBuffer();
  final buffer = StringBuffer();

  for (final filename in files) {
    final file = File(p.join(srcDir.path, filename));
    if (!file.existsSync()) {
      print('Warning: \${file.path} not found.');
      continue;
    }

    final lines = file.readAsLinesSync();

    buffer.writeln('// --- \$filename ---');
    for (var line in lines) {
      // Ignore imports within the library
      if ((line.startsWith('import ') || line.startsWith('export')) &&
          (line.contains('.dart') || line.contains('package:glush/'))) {
        continue;
      }
      if (line.startsWith('library ')) {
        continue;
      }

      if (line.startsWith('import') && line.contains('dart:')) {
        imports.writeln(line);
        continue;
      }

      // Remove library prefixes used for intra-package imports since they are all one file now
      line = line.replaceAll('sm.', '');

      buffer.writeln(line);
    }
    buffer.writeln();
  }

  // No escaping needed for $ or \ since we are writing into a raw string r'''
  final escaped = buffer.toString();

  final output = '''// Auto-generated by tool/bundle_runtime.dart
// Contains the combined source code of the glush runtime for standalone generation.

const String runtimeBundle = r\'''
$imports
$escaped
\''';
''';

  File(p.join(srcDir.path, 'runtime_bundle.dart')).writeAsStringSync(output);
  print('Generated lib/src/runtime_bundle.dart successfully.');
}
